telegram_bundle:
  resource: '@TelegramBundle/config/routes.yaml'
  prefix: #здесь можно указать любой префикс, по умолчанию бандл использует пути "/telegram/...", можно оставить пустым
  name_prefix:  # не используйте префикс имен, иначе некоторые функции работать не будут